server:
  port: 80
#  ssl.key-store: classpath:123.pfx
#  ssl.key-store-password: 123
#  ssl.keyStoreType: PKCS12
  
SSL:
  port: 80
  redirectPort: 443
  
mybatis:
  config-location: classpath:mybatis-config.xml       # mybatis配置文件所在路径
#  type-aliases-package: cn.ssm.model    # 所有Entity别名类所在包
  mapper-locations: classpath:cn/ssm/**/dao/*.xml                       # mapper映射文件

#mappers 通用mappers配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

spring:
#  profiles:
#     active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://47.107.51.167:3306/checkin_database            # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 100                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  jackson:
     date-format: yyyy/MM/dd HH:mm:ss
     time-zone: GMT+8
  mvc:
    view:
      prefix: / #前缀
      suffix: .html #后缀
  mail: # JavaMailSender 邮件发送的配置
    host: smtp.163.com
    username: 123@163.com
    password: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 100MB #单个数据的大小
      max-request-size: 100MB #总数据的大小
  thymeleaf:
    cache: false
          
# redis配置，以下有默认配置的也可以使用默认配置
redis: 
  host: 127.0.0.1
  port: 6379
  timeout: 0 # 连接超时时间（毫秒）   
  pool:
    max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
    max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 8 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
    
# wx-java-tool配置
wx:
  miniapp:
    configs:
        - appid: wx9394d0eb96664c21 #微信小程序的appid
          secret: f5c76ac2bb4daac3fc70d43fde71fbed #微信小程序的Secret
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
  mp:
    configs:
      - appId: wxc5f904a3636a3cbb #（一个公众号的appid）
        secret: 198c6f8997a4fa6ba4eff7b97484c001 #（公众号的appsecret）
        token: wxToken #（接口配置里的Token值）
        aesKey:   #（接口配置里的EncodingAESKey值）

baidu: 
  character-recognition: 
    apiKey: g8fOHQL6mgqnUkAsl9PqNR2d
    secretKey: Z2sixe9EmKji5lhhfVm7BPVW5VlV3yOc
    
    
  
     
  
     
